# This Dockerfile describes an image intended to provide
# a base development environment for a web-application written
# using NodeJS.

FROM ubuntu:14.04
MAINTAINER "Sophia Hudson <sophialhudson@gmail.com>"
LABEL \
  multi.version="0.0.1" \
  multi.env="node-web" \
  multi.description="A NodeJS environment for building web applications"
